config/routes.rb
Rails.application.routes.draw do
  root 'landing_page#index'

  resources :emails, only: [:create]

  get 'confirm_email/:token', to: 'emails#confirm_email', as: 'email_confirmation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
  has_secure_token :confirmation_token

  validates :to, :body, :send_date_on, presence: true
  validates :to, 'valid_email_2/email': true

  scope :today_emails, -> { where(send_date_on: Date.current) }

  def from
    ENV.fetch('MAILGUN_SMTP_LOGIN', '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  def create
    @email = Email.new(email_params)

    if verify_recaptcha(model: @email) && @email.save
      DearMeMailer.token_confirmation(@email).deliver_later
      return redirect_to root_path, notice: 'Email verification sent!'
    end

    flash[:alert] = 'The email could not be sent.'
    render 'landing_page/index', status: :unprocessable_entity
  end

  def confirm_email
    if ConfirmEmailService.perform(params[:token])
      return redirect_to root_path, notice: 'Email confirmed!'
    end

    redirect_to root_path, alert: 'Token invalid or expired.'
  end

  private

  def email_params
    params.require(:email).permit(:to, :body, :send_date_on)
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
    @email = Email.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message(key, message)
    capture do
      Array(message).each { |element| concat content_tag(:li, element) }
    end
  end
end

app/views/landing_page/index.html.erb
<section>
  <h2>
    Dear future me.
  </h2>

  <p>
    Write an e-mail to yourself, set the date you want to receive it and send it! Simple as that!
  </p>

  <%= form_for @email, url: emails_path, method: :post do |f| %>
    <%= f.text_field :to, placeholder: :to %>
    <%= f.text_area :body, placeholder: :body %>
    <%= f.label :send_date_on %>
    <%= f.date_select :send_date_on, end_year: Time.current.year + 50 %>
    <p class="italic">PS: We will send a confirmation e-mail beforehand in order to avoid spam.</p>
    <%= invisible_recaptcha_tags text: t('create', scope: 'helpers.submit', model: @email.model_name.human) %>
  <% end %>

</section>

app/views/layouts/_messages.html.erb
<div>
  <ul>
    <% flash.each do |key, value| %>
      <%= flash_message(key, value) %>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DearMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto+Slab">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>